[package]
name = "source"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# aux5 = { path = "auxiliary" }
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"]}
cortex-m-rt = { version = "0.7.3", features = ["device"] }
# nb = "1"
# embedded-dma = "0.2.0"
# bxcan = "0.7"
# void = { default-features = false, version = "1.0.2" }
# embedded-hal = { features = ["unproven"], version = "0.2.7" }
fugit = "0.3.6"
fugit-timer = "0.1.3"
# rtic-monotonic = { version = "1.0", optional = true }
# bitflags = "1.3.2"
stm32f3xx-hal = { version = "0.9.2", features = ["ld", "rt", "stm32f303xc"] }
usbd-serial = "0.1.1"
usb-device = "0.2.9"
panic-halt = "0.2.0"
cortex-m-semihosting = "0.5.0"
usbd-human-interface-device = "0.3.2"

[dependencies.stm32f3]
version = "0.15.1"
features = ["stm32f303"]
