pub struct ControllerState {
    pub up: bool,
    pub down: bool,
    pub left: bool,
    pub right: bool,
    pub start: bool,
    pub back: bool,
    pub left_thumb: bool,
    pub right_thumb: bool,
    pub left_shoulder: bool,
    pub right_shoulder: bool,
    pub guide: bool,
    pub a: bool,
    pub b: bool,
    pub x: bool,
    pub y: bool,
    pub left_thumb_x: f32,
    pub left_thumb_y: f32,
    pub right_thumb_x: f32,
    pub right_thumb_y: f32,
    pub left_trigger: f32,
    pub right_trigger: f32,
    pub other_value_0: f32,
    pub other_value_1: f32,
}

impl ControllerState {
    pub fn new() -> ControllerState {
        ControllerState {
            up: false,
            down: false,
            left: false,
            right: false,
            start: false,
            back: false,
            left_thumb: false,
            right_thumb: false,
            left_shoulder: false,
            right_shoulder: false,
            guide: false,
            a: false,
            b: false,
            x: false,
            y: false,
            left_thumb_x: 0.0f32,
            left_thumb_y: 0.0f32,
            right_thumb_x: 0.0f32,
            right_thumb_y: 0.0f32,
            left_trigger: 0.0f32,
            right_trigger: 0.0f32,
            other_value_0: 0.0f32,
            other_value_1: 0.0f32,
        }
    }
}
